language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install tidy
  - sudo apt-get install -y libreoffice python3-uno
  - libreoffice '--accept=socket,host=127.0.0.1,port=8100;urp;' &

install:
  - pip install -U setuptools
  - pip install -e .
  - pip install atelier
  - inv install
  - pip freeze

script:
  - inv prep
  - inv test
  - inv bd
